controller:
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      alb.ingress.kubernetes.io/subnets: eywa-public-ap-southeast-2a, eywa-public-ap-southeast-2b
