name: Random

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        shell: bash
        run: |
          echo "Hello worldss"
