name: Deploy Apps

on:
  workflow_run:
    workflows: ["Random", "RandomNew"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        shell: bash
        run: |
          echo "Hello world"
