name: 'Destroy Infrastructure'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Are you sure you want to destroy the infrastructure'
        required: true
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_VAR_region: ap-southeast-2
      TF_VAR_environment: prod
      TF_VAR_account: 687568543601

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: infrastructure/environments/prod

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Assume Role
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::687568543601:role/eywa-admin
        aws-region: ap-southeast-2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Destroy
      run: terraform destroy --auto-approve
